//! OpenCode session identity via a global plugin, not sqlite discovery.
//!
//! HK-Craft writes `plugins/hk-craft.js` into OpenCode's config dir. When a PTY
//! spawns `opencode`, it injects localhost hook env vars; the plugin reports the
//! top-level session id over a JSON-line TCP socket. Other terminals are inert
//! because they lack those variables.

use std::io::{BufRead, BufReader};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::time::Duration;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter};

pub const PLUGIN_FILE_NAME: &str = "hk-craft.js";
pub const PLUGIN_MARKER: &str = "AUTO-GENERATED by HK-Craft";

const READ_TIMEOUT: Duration = Duration::from_secs(2);
const MAX_LINE_BYTES: usize = 8 * 1024;

static ENDPOINT: OnceLock<HookEndpoint> = OnceLock::new();

#[derive(Debug, Clone)]
pub struct HookEndpoint {
    pub port: u16,
    pub token: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct AgentSessionEvent {
    pub session_id: String,
    pub opencode_id: String,
}

#[derive(Debug, Deserialize)]
struct HookLine {
    token: String,
    #[serde(default)]
    session_id: Option<String>,
    #[serde(default)]
    pane: Option<String>,
}

pub const PLUGIN_JS: &str = r#"// HK-Craft ↔ opencode bridge — AUTO-GENERATED by HK-Craft, do not edit.
// Reports the top-level session id so HK-Craft can resume with --session.
// Inert outside HK-Craft (no HK_CRAFT_HOOK_PORT / TOKEN / SESSION).
export const HkCraftSession = async () => {
  const port = process.env.HK_CRAFT_HOOK_PORT
  const token = process.env.HK_CRAFT_HOOK_TOKEN
  const pane = process.env.HK_CRAFT_SESSION
  if (!port || !token || !pane) return {}
  let sessionId = ""
  const validId = (id) =>
    typeof id === "string"
    && id.length > 0
    && id.length <= 64
    && /^[A-Za-z0-9._-]+$/.test(id)
  const send = (obj) => {
    try {
      obj.token = token
      obj.pane = pane
      if (sessionId) obj.session_id = sessionId
      const payload = JSON.stringify(obj) + "\n"
      const p = Number(port)
      Bun.connect({ hostname: "127.0.0.1", port: p })
        .then((s) => {
          s.write(payload)
          s.end()
        })
        .catch(() => {})
    } catch (_) {}
  }
  return {
    event: async ({ event }) => {
      const props = (event && event.properties) || {}
      const info = props.info || {}
      // Root session only: subagents carry parentID and must not steal resume identity.
      const candidate = props.sessionID || info.sessionID || (!info.parentID && info.id)
      if (candidate && validId(candidate)) {
        const first = !sessionId
        sessionId = candidate
        if (first) send({ kind: "session-start" })
      }
    },
  }
}
"#;

pub fn start(app: AppHandle) {
    match TcpListener::bind("127.0.0.1:0") {
        Ok(listener) => {
            let port = match listener.local_addr() {
                Ok(addr) => addr.port(),
                Err(err) => {
                    eprintln!("opencode hook bind addr failed: {err}");
                    let _ = ensure_plugin(false);
                    return;
                }
            };
            let token = uuid::Uuid::new_v4().to_string();
            if ENDPOINT.set(HookEndpoint { port, token: token.clone() }).is_err() {
                let _ = ensure_plugin(false);
                return;
            }
            std::thread::Builder::new()
                .name("opencode-hook".into())
                .spawn(move || accept_loop(app, listener, token))
                .ok();
        }
        Err(err) => {
            eprintln!("opencode hook listen failed: {err}");
        }
    }
    let _ = ensure_plugin(false);
}

pub fn apply_spawn_env(cmd: &mut portable_pty::CommandBuilder, command: &str, session_id: &str) {
    let Some(vars) = hook_env_vars(command, session_id, ENDPOINT.get()) else {
        return;
    };
    let _ = ensure_plugin(true);
    for (key, value) in vars {
        cmd.env(key, value);
    }
}

pub fn hook_env_vars(
    command: &str,
    session_id: &str,
    hook: Option<&HookEndpoint>,
) -> Option<Vec<(String, String)>> {
    if crate::session::agent_bin(command) != "opencode" {
        return None;
    }
    if !is_agent_session(session_id) {
        return None;
    }
    let hook = hook?;
    Some(vec![
        ("HK_CRAFT_HOOK_PORT".into(), hook.port.to_string()),
        ("HK_CRAFT_HOOK_TOKEN".into(), hook.token.clone()),
        ("HK_CRAFT_SESSION".into(), session_id.to_string()),
    ])
}

pub fn valid_session_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 64
        && id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
}

pub fn is_agent_session(session_id: &str) -> bool {
    matches!(crate::runner::parse_session_id(session_id), Some((_, "agent", _)))
}

pub fn parse_hook_line(line: &str, expected_token: &str) -> Option<AgentSessionEvent> {
    if line.len() > MAX_LINE_BYTES {
        return None;
    }
    let value: HookLine = serde_json::from_str(line.trim()).ok()?;
    if value.token != expected_token {
        return None;
    }
    let opencode_id = value.session_id.filter(|id| valid_session_id(id))?;
    let session_id = value.pane.filter(|pane| is_agent_session(pane))?;
    Some(AgentSessionEvent {
        session_id,
        opencode_id,
    })
}

pub fn resolve_opencode_config_dir(
    config_dir: Option<&Path>,
    xdg_config_home: Option<&Path>,
    home: Option<&Path>,
) -> Option<PathBuf> {
    if let Some(dir) = config_dir.filter(|path| !path.as_os_str().is_empty()) {
        return Some(dir.to_path_buf());
    }
    if let Some(xdg) = xdg_config_home.filter(|path| !path.as_os_str().is_empty()) {
        return Some(xdg.join("opencode"));
    }
    Some(home?.join(".config").join("opencode"))
}

fn current_opencode_config_dir() -> Option<PathBuf> {
    let config_dir = std::env::var_os("OPENCODE_CONFIG_DIR").map(PathBuf::from);
    let xdg = std::env::var_os("XDG_CONFIG_HOME").map(PathBuf::from);
    let home = dirs::home_dir();
    resolve_opencode_config_dir(config_dir.as_deref(), xdg.as_deref(), home.as_deref())
}

pub fn plugin_path_for(config_dir: &Path) -> PathBuf {
    config_dir.join("plugins").join(PLUGIN_FILE_NAME)
}

pub fn ensure_plugin(create: bool) -> std::io::Result<bool> {
    let Some(dir) = current_opencode_config_dir() else {
        return Ok(false);
    };
    if !dir.exists() && !create {
        return Ok(false);
    }
    write_plugin(&plugin_path_for(&dir), PLUGIN_JS)
}

pub fn write_plugin(path: &Path, contents: &str) -> std::io::Result<bool> {
    if path.exists() {
        if let Ok(existing) = std::fs::read_to_string(path) {
            if existing == contents {
                return Ok(false);
            }
            if !existing.contains(PLUGIN_MARKER) {
                return Ok(false);
            }
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("js.tmp");
    std::fs::write(&tmp, contents)?;
    std::fs::rename(&tmp, path)?;
    Ok(true)
}

fn accept_loop(app: AppHandle, listener: TcpListener, token: String) {
    for incoming in listener.incoming() {
        let Ok(stream) = incoming else {
            continue;
        };
        let _ = stream.set_read_timeout(Some(READ_TIMEOUT));
        let mut reader = BufReader::new(stream);
        let mut line = String::new();
        if reader.read_line(&mut line).is_err() || line.is_empty() {
            continue;
        }
        let Some(event) = parse_hook_line(&line, &token) else {
            continue;
        };
        let _ = app.emit("agent-session", event);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plugin_js_is_inert_without_env() {
        assert!(PLUGIN_JS.contains(PLUGIN_MARKER));
        assert!(PLUGIN_JS.contains("if (!port || !token || !pane) return {}"));
        assert!(PLUGIN_JS.contains("parentID"));
    }

    #[test]
    fn session_id_charset_and_length() {
        assert!(valid_session_id("ses_f935340b2ffeMcewmF91GLLwvV"));
        assert!(valid_session_id("a-b_c.d"));
        assert!(!valid_session_id(""));
        assert!(!valid_session_id("abc; rm"));
        assert!(!valid_session_id(&"a".repeat(65)));
    }

    #[test]
    fn parse_hook_line_accepts_matching_token_and_agent_pane() {
        let line = r#"{"kind":"session-start","token":"t1","session_id":"ses_abc","pane":"proj:agent:a1"}"#;
        let event = parse_hook_line(line, "t1").expect("valid line");
        assert_eq!(event.session_id, "proj:agent:a1");
        assert_eq!(event.opencode_id, "ses_abc");
    }

    #[test]
    fn parse_hook_line_rejects_wrong_token_and_non_agent_panes() {
        let line = r#"{"token":"nope","session_id":"ses_abc","pane":"proj:agent:a1"}"#;
        assert!(parse_hook_line(line, "t1").is_none());
        let runner = r#"{"token":"t1","session_id":"ses_abc","pane":"proj:runner:r1"}"#;
        assert!(parse_hook_line(runner, "t1").is_none());
        let missing = r#"{"token":"t1","pane":"proj:agent:a1"}"#;
        assert!(parse_hook_line(missing, "t1").is_none());
    }

    #[test]
    fn config_dir_prefers_explicit_then_xdg_then_home() {
        assert_eq!(
            resolve_opencode_config_dir(Some(Path::new("D:/oc-config")), None, None),
            Some(PathBuf::from("D:/oc-config"))
        );
        assert_eq!(
            resolve_opencode_config_dir(None, Some(Path::new("D:/xdg")), None),
            Some(PathBuf::from("D:/xdg").join("opencode"))
        );
        assert_eq!(
            resolve_opencode_config_dir(None, None, Some(Path::new("C:/Users/me"))),
            Some(PathBuf::from("C:/Users/me").join(".config").join("opencode"))
        );
        assert_eq!(resolve_opencode_config_dir(None, None, None), None);
    }

    #[test]
    fn hook_env_only_for_opencode_agent_panes() {
        let hook = HookEndpoint {
            port: 4321,
            token: "tok".into(),
        };
        let vars = hook_env_vars("opencode", "proj:agent:a1", Some(&hook)).expect("env");
        assert!(vars.iter().any(|(k, v)| k == "HK_CRAFT_HOOK_PORT" && v == "4321"));
        assert!(vars.iter().any(|(k, v)| k == "HK_CRAFT_HOOK_TOKEN" && v == "tok"));
        assert!(vars.iter().any(|(k, v)| k == "HK_CRAFT_SESSION" && v == "proj:agent:a1"));
        assert!(hook_env_vars("cursor-agent", "proj:agent:a1", Some(&hook)).is_none());
        assert!(hook_env_vars("opencode", "proj:runner:r1", Some(&hook)).is_none());
        assert!(hook_env_vars("opencode", "proj:agent:a1", None).is_none());
    }

    #[test]
    fn write_plugin_skips_foreign_files_and_is_idempotent() {
        let root = std::env::temp_dir().join(format!("aw-oc-plugin-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let path = plugin_path_for(&root);
        assert!(write_plugin(&path, PLUGIN_JS).unwrap());
        assert!(std::fs::read_to_string(&path).unwrap().contains(PLUGIN_MARKER));
        assert!(!write_plugin(&path, PLUGIN_JS).unwrap());

        std::fs::write(&path, "// someone else's plugin\n").unwrap();
        assert!(!write_plugin(&path, PLUGIN_JS).unwrap());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "// someone else's plugin\n");
        let _ = std::fs::remove_dir_all(&root);
    }
}
