//! OpenCode live session identity via a global plugin.
//!
//! HK-Craft writes `plugins/hk-craft.js` into OpenCode's config dir. When a PTY
//! spawns `opencode`, it injects localhost hook env vars; the plugin reports the
//! top-level session id over TCP and a JSON inbox file. Other terminals are inert
//! because they lack those variables. Historical sessions for a project cwd are
//! listed separately by `opencode_discover` from `opencode.db`.

use std::fs;
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::time::Duration;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter};

pub const PLUGIN_FILE_NAME: &str = "hk-craft.js";
pub const PLUGIN_MARKER: &str = "AUTO-GENERATED by HK-Craft";

const READ_TIMEOUT: Duration = Duration::from_secs(2);
const MAX_LINE_BYTES: usize = 8 * 1024;
const INBOX_POLL: Duration = Duration::from_millis(400);

static ENDPOINT: OnceLock<HookEndpoint> = OnceLock::new();

#[derive(Debug, Clone)]
pub struct HookEndpoint {
    pub port: u16,
    pub token: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct AgentSessionEvent {
    pub session_id: String,
    pub opencode_id: String,
}

#[derive(Debug, Deserialize)]
struct HookLine {
    token: String,
    #[serde(default)]
    session_id: Option<String>,
    #[serde(default)]
    pane: Option<String>,
}

pub const PLUGIN_JS: &str = r#"// HK-Craft ↔ opencode bridge — AUTO-GENERATED by HK-Craft, do not edit.
// Reports the top-level session id so HK-Craft can resume with --session.
// Inert outside HK-Craft (no HK_CRAFT_HOOK_PORT / TOKEN / SESSION).
const plugin = async (ctx) => {
  const port = process.env.HK_CRAFT_HOOK_PORT
  const token = process.env.HK_CRAFT_HOOK_TOKEN
  const pane = process.env.HK_CRAFT_SESSION
  if (!port || !token || !pane) return {}
  let sessionId = ""
  const validId = (id) =>
    typeof id === "string"
    && id.length > 4
    && id.length <= 64
    && /^ses_[A-Za-z0-9._-]+$/.test(id)
  const send = () => {
    if (!sessionId) return
    const obj = { kind: "session-start", token, pane, session_id: sessionId }
    const body = JSON.stringify(obj)
    const payload = body + "\n"
    const p = Number(port)
    try {
      const home = process.env.USERPROFILE || process.env.HOME || ""
      if (home) {
        const dir = String(home).replace(/\\/g, "/") + "/.hk-craft/opencode-hook"
        const name = pane.replace(/[^A-Za-z0-9._-]/g, "_") + ".json"
        void import("node:fs").then((fs) => {
          fs.mkdirSync(dir, { recursive: true })
          const dest = dir + "/" + name
          fs.writeFileSync(dest + ".tmp", body)
          fs.renameSync(dest + ".tmp", dest)
        }).catch(() => {})
      }
    } catch (_) {}
    try {
      void fetch("http://127.0.0.1:" + p + "/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: payload,
      }).catch(() => {})
    } catch (_) {}
    try {
      void import("node:net").then((net) => {
        const sock = net.connect({ host: "127.0.0.1", port: p }, () => {
          sock.write(payload)
          sock.end()
        })
        sock.on("error", () => {})
      }).catch(() => {})
    } catch (_) {}
  }
  const report = (id) => {
    if (!validId(id) || sessionId) return
    sessionId = id
    send()
    setTimeout(send, 250)
    setTimeout(send, 1000)
  }
  const fromEvent = (event) => {
    const props = (event && (event.properties || event.data)) || {}
    const info = props.info || {}
    if (info.parentID || props.parentID) return
    report(props.sessionID || info.sessionID || info.id)
  }
  const client = ctx && ctx.client
  if (client && client.session && typeof client.session.list === "function") {
    const poll = async () => {
      if (sessionId) return
      try {
        const res = await client.session.list()
        const list = Array.isArray(res) ? res
          : Array.isArray(res && res.data) ? res.data
          : []
        let best = null
        for (const item of list) {
          if (!item || item.parentID) continue
          if (!validId(item.id)) continue
          const updated = (item.time && item.time.updated) || 0
          const prev = (best && best.time && best.time.updated) || 0
          if (!best || updated >= prev) best = item
        }
        if (best) report(best.id)
      } catch (_) {}
    }
    void poll()
    setTimeout(poll, 800)
    setTimeout(poll, 2500)
  }
  return {
    event: async ({ event }) => { fromEvent(event) },
    "chat.message": async (input) => { report(input && input.sessionID) },
    "tool.execute.before": async (input) => { report(input && input.sessionID) },
  }
}
export const HkCraftSession = plugin
export default { id: "hk-craft", server: plugin }
"#;

pub fn start(app: AppHandle) {
    match TcpListener::bind("127.0.0.1:0") {
        Ok(listener) => {
            let port = match listener.local_addr() {
                Ok(addr) => addr.port(),
                Err(err) => {
                    eprintln!("opencode hook bind addr failed: {err}");
                    let _ = ensure_plugin(false);
                    return;
                }
            };
            let token = uuid::Uuid::new_v4().to_string();
            if ENDPOINT.set(HookEndpoint { port, token: token.clone() }).is_err() {
                let _ = ensure_plugin(false);
                return;
            }
            let inbox_app = app.clone();
            let inbox_token = token.clone();
            std::thread::Builder::new()
                .name("opencode-hook-inbox".into())
                .spawn(move || poll_inbox(inbox_app, inbox_token))
                .ok();
            std::thread::Builder::new()
                .name("opencode-hook".into())
                .spawn(move || accept_loop(app, listener, token))
                .ok();
        }
        Err(err) => {
            eprintln!("opencode hook listen failed: {err}");
        }
    }
    let _ = ensure_plugin(false);
    if let Some(dir) = hook_inbox_dir() {
        let _ = fs::create_dir_all(&dir);
    }
}

pub fn prepare_spawn_env(command: &str, session_id: &str) -> Vec<(String, String)> {
    let Some(vars) = hook_env_vars(command, session_id, ENDPOINT.get()) else {
        return Vec::new();
    };
    let _ = ensure_plugin(true);
    vars
}

pub fn hook_env_vars(
    command: &str,
    session_id: &str,
    hook: Option<&HookEndpoint>,
) -> Option<Vec<(String, String)>> {
    if crate::session::agent_bin(command) != "opencode" {
        return None;
    }
    if !is_agent_session(session_id) {
        return None;
    }
    let hook = hook?;
    Some(vec![
        ("HK_CRAFT_HOOK_PORT".into(), hook.port.to_string()),
        ("HK_CRAFT_HOOK_TOKEN".into(), hook.token.clone()),
        ("HK_CRAFT_SESSION".into(), session_id.to_string()),
    ])
}

/// `set KEY=value&` prefixes (no quotes). portable-pty quotes the whole `/c`
/// argument; nested `set "KEY=value"` becomes `\"` and cmd.exe never assigns.
pub fn windows_cmd_env_prefix(vars: &[(String, String)]) -> String {
    vars.iter()
        .map(|(key, value)| {
            let value = value.replace(['"', '&', '|', '%', '<', '>', ' ', '^'], "");
            format!("set {key}={value}&")
        })
        .collect()
}

/// Blank host-terminal identity so a nested `dsh --profile` cannot inherit
/// Windows Terminal / Cursor `WT_SESSION` or a 1.x `TERM_PROGRAM_VERSION`.
pub fn windows_cmd_clear_host_terminal_prefix() -> String {
    [
        "WT_SESSION",
        "WT_PROFILE_ID",
        "WT_DEFAULT_PROFILE",
        "TERM_PROGRAM_PATH",
        "TERMINAL_EMULATOR",
    ]
    .iter()
    .map(|key| format!("set {key}=&"))
    .collect()
}

pub fn valid_session_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 64
        && id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
}

pub fn valid_opencode_id(id: &str) -> bool {
    id.starts_with("ses_") && valid_session_id(id)
}

pub fn is_agent_session(session_id: &str) -> bool {
    matches!(crate::runner::parse_session_id(session_id), Some((_, "agent", _)))
}

pub fn parse_hook_line(line: &str, expected_token: &str) -> Option<AgentSessionEvent> {
    if line.len() > MAX_LINE_BYTES {
        return None;
    }
    let value: HookLine = serde_json::from_str(line.trim()).ok()?;
    if value.token != expected_token {
        return None;
    }
    let opencode_id = value.session_id.filter(|id| valid_opencode_id(id))?;
    let session_id = value.pane.filter(|pane| is_agent_session(pane))?;
    Some(AgentSessionEvent {
        session_id,
        opencode_id,
    })
}

pub fn first_json_line(text: &str) -> Option<&str> {
    text.lines()
        .map(str::trim)
        .find(|line| line.starts_with('{') && line.len() <= MAX_LINE_BYTES)
}

pub fn resolve_opencode_config_dir(
    config_dir: Option<&Path>,
    xdg_config_home: Option<&Path>,
    home: Option<&Path>,
) -> Option<PathBuf> {
    if let Some(dir) = config_dir.filter(|path| !path.as_os_str().is_empty()) {
        return Some(dir.to_path_buf());
    }
    if let Some(xdg) = xdg_config_home.filter(|path| !path.as_os_str().is_empty()) {
        return Some(xdg.join("opencode"));
    }
    Some(home?.join(".config").join("opencode"))
}

fn current_opencode_config_dir() -> Option<PathBuf> {
    let config_dir = std::env::var_os("OPENCODE_CONFIG_DIR").map(PathBuf::from);
    let xdg = std::env::var_os("XDG_CONFIG_HOME").map(PathBuf::from);
    let home = dirs::home_dir();
    resolve_opencode_config_dir(config_dir.as_deref(), xdg.as_deref(), home.as_deref())
}

pub fn plugin_path_for(config_dir: &Path) -> PathBuf {
    config_dir.join("plugins").join(PLUGIN_FILE_NAME)
}

pub fn hook_inbox_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|home| home.join(".hk-craft").join("opencode-hook"))
}

pub fn ensure_plugin(create: bool) -> std::io::Result<bool> {
    let Some(dir) = current_opencode_config_dir() else {
        return Ok(false);
    };
    if !dir.exists() && !create {
        return Ok(false);
    }
    write_plugin(&plugin_path_for(&dir), PLUGIN_JS)
}

pub fn write_plugin(path: &Path, contents: &str) -> std::io::Result<bool> {
    if path.exists() {
        if let Ok(existing) = std::fs::read_to_string(path) {
            if existing == contents {
                return Ok(false);
            }
            if !existing.contains(PLUGIN_MARKER) {
                return Ok(false);
            }
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("js.tmp");
    std::fs::write(&tmp, contents)?;
    std::fs::rename(&tmp, path)?;
    Ok(true)
}

fn emit_event(app: &AppHandle, event: AgentSessionEvent) {
    let _ = app.emit("agent-session", event);
}

fn accept_loop(app: AppHandle, listener: TcpListener, token: String) {
    for incoming in listener.incoming() {
        let Ok(stream) = incoming else {
            continue;
        };
        handle_conn(&app, stream, &token);
    }
}

fn handle_conn(app: &AppHandle, stream: TcpStream, token: &str) {
    let _ = stream.set_read_timeout(Some(READ_TIMEOUT));
    let mut writer = stream.try_clone().ok();
    let mut reader = BufReader::new(stream);
    let mut buf = String::new();
    loop {
        let mut line = String::new();
        match reader.read_line(&mut line) {
            Ok(0) => break,
            Ok(_) => {
                buf.push_str(&line);
                if buf.len() > MAX_LINE_BYTES * 8 {
                    break;
                }
                if let Some(json) = first_json_line(&buf) {
                    if let Some(event) = parse_hook_line(json, token) {
                        emit_event(app, event);
                    }
                    break;
                }
            }
            Err(_) => break,
        }
    }
    if let Some(mut out) = writer.take() {
        let _ = out.write_all(b"HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n");
    }
}

fn poll_inbox(app: AppHandle, token: String) {
    if let Some(dir) = hook_inbox_dir() {
        let _ = fs::create_dir_all(&dir);
    }
    loop {
        std::thread::sleep(INBOX_POLL);
        let Some(dir) = hook_inbox_dir() else {
            continue;
        };
        let Ok(entries) = fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
                continue;
            }
            let Ok(raw) = fs::read_to_string(&path) else {
                continue;
            };
            if let Some(json) = first_json_line(&raw) {
                if let Some(event) = parse_hook_line(json, &token) {
                    emit_event(&app, event);
                }
            }
            let _ = fs::remove_file(&path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plugin_js_is_inert_without_env() {
        assert!(PLUGIN_JS.contains(PLUGIN_MARKER));
        assert!(PLUGIN_JS.contains("if (!port || !token || !pane) return {}"));
        assert!(PLUGIN_JS.contains("parentID"));
        assert!(PLUGIN_JS.contains(r#"id: "hk-craft""#));
        assert!(PLUGIN_JS.contains("chat.message"));
        assert!(PLUGIN_JS.contains("opencode-hook"));
        assert!(PLUGIN_JS.contains("session.list"));
        assert!(PLUGIN_JS.contains("event.properties || event.data"));
        assert!(PLUGIN_JS.contains("ses_"));
    }

    #[test]
    fn session_id_charset_and_length() {
        assert!(valid_session_id("ses_f935340b2ffeMcewmF91GLLwvV"));
        assert!(valid_session_id("a-b_c.d"));
        assert!(!valid_session_id(""));
        assert!(!valid_session_id("abc; rm"));
        assert!(!valid_session_id(&"a".repeat(65)));
        assert!(valid_opencode_id("ses_f935340b2ffeMcewmF91GLLwvV"));
        assert!(!valid_opencode_id("msg_abc"));
        assert!(!valid_opencode_id("a-b_c.d"));
    }

    #[test]
    fn parse_hook_line_accepts_matching_token_and_agent_pane() {
        let line = r#"{"kind":"session-start","token":"t1","session_id":"ses_abc","pane":"proj:agent:a1"}"#;
        let event = parse_hook_line(line, "t1").expect("valid line");
        assert_eq!(event.session_id, "proj:agent:a1");
        assert_eq!(event.opencode_id, "ses_abc");
    }

    #[test]
    fn parse_hook_line_rejects_wrong_token_and_non_agent_panes() {
        let line = r#"{"token":"nope","session_id":"ses_abc","pane":"proj:agent:a1"}"#;
        assert!(parse_hook_line(line, "t1").is_none());
        let runner = r#"{"token":"t1","session_id":"ses_abc","pane":"proj:runner:r1"}"#;
        assert!(parse_hook_line(runner, "t1").is_none());
        let missing = r#"{"token":"t1","pane":"proj:agent:a1"}"#;
        assert!(parse_hook_line(missing, "t1").is_none());
        let message_id = r#"{"token":"t1","session_id":"msg_abc","pane":"proj:agent:a1"}"#;
        assert!(parse_hook_line(message_id, "t1").is_none());
    }

    #[test]
    fn first_json_line_skips_http_headers() {
        let http = "POST / HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n{\"kind\":\"session-start\",\"token\":\"t1\",\"session_id\":\"ses_abc\",\"pane\":\"proj:agent:a1\"}\r\n";
        let json = first_json_line(http).expect("json");
        let event = parse_hook_line(json, "t1").expect("valid");
        assert_eq!(event.opencode_id, "ses_abc");
    }

    #[test]
    fn windows_cmd_prefix_sets_unquoted_env() {
        let prefix = windows_cmd_env_prefix(&[
            ("HK_CRAFT_HOOK_PORT".into(), "9".into()),
            ("HK_CRAFT_SESSION".into(), "proj:agent:a1".into()),
        ]);
        assert_eq!(prefix, "set HK_CRAFT_HOOK_PORT=9&set HK_CRAFT_SESSION=proj:agent:a1&");
        assert!(!prefix.contains('"'));
    }

    #[test]
    fn windows_cmd_clear_host_terminal_unsets_wt_session() {
        let prefix = windows_cmd_clear_host_terminal_prefix();
        assert!(prefix.contains("set WT_SESSION=&"));
        assert!(prefix.contains("set TERMINAL_EMULATOR=&"));
        assert!(!prefix.contains('"'));
    }

    #[test]
    fn config_dir_prefers_explicit_then_xdg_then_home() {
        assert_eq!(
            resolve_opencode_config_dir(Some(Path::new("D:/oc-config")), None, None),
            Some(PathBuf::from("D:/oc-config"))
        );
        assert_eq!(
            resolve_opencode_config_dir(None, Some(Path::new("D:/xdg")), None),
            Some(PathBuf::from("D:/xdg").join("opencode"))
        );
        assert_eq!(
            resolve_opencode_config_dir(None, None, Some(Path::new("C:/Users/me"))),
            Some(PathBuf::from("C:/Users/me").join(".config").join("opencode"))
        );
        assert_eq!(resolve_opencode_config_dir(None, None, None), None);
    }

    #[test]
    fn hook_env_only_for_opencode_agent_panes() {
        let hook = HookEndpoint {
            port: 4321,
            token: "tok".into(),
        };
        let vars = hook_env_vars("opencode", "proj:agent:a1", Some(&hook)).expect("env");
        assert!(vars.iter().any(|(k, v)| k == "HK_CRAFT_HOOK_PORT" && v == "4321"));
        assert!(vars.iter().any(|(k, v)| k == "HK_CRAFT_HOOK_TOKEN" && v == "tok"));
        assert!(vars.iter().any(|(k, v)| k == "HK_CRAFT_SESSION" && v == "proj:agent:a1"));
        assert!(hook_env_vars("cursor-agent", "proj:agent:a1", Some(&hook)).is_none());
        assert!(hook_env_vars("opencode", "proj:runner:r1", Some(&hook)).is_none());
        assert!(hook_env_vars("opencode", "proj:agent:a1", None).is_none());
    }

    #[test]
    fn write_plugin_skips_foreign_files_and_is_idempotent() {
        let root = std::env::temp_dir().join(format!("aw-oc-plugin-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let path = plugin_path_for(&root);
        assert!(write_plugin(&path, PLUGIN_JS).unwrap());
        assert!(std::fs::read_to_string(&path).unwrap().contains(PLUGIN_MARKER));
        assert!(!write_plugin(&path, PLUGIN_JS).unwrap());

        std::fs::write(&path, "// someone else's plugin\n").unwrap();
        assert!(!write_plugin(&path, PLUGIN_JS).unwrap());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "// someone else's plugin\n");
        let _ = std::fs::remove_dir_all(&root);
    }
}
